site_name: Emotions for Engineers
site_url: https://florindottudosedotcom.github.io/emotions-for-engineers/
repo_url: https://github.com/florindottudosedotcom/emotions-for-engineers

theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr
    - name: हिन्दी
      link: ./hi/
      lang: hi
    - name: Italiano
      link: ./it/
      lang: it
    - name: 日本語
      link: ./ja/
      lang: ja
    - name: Português
      link: ./pt/
      lang: pt
    - name: Română
      link: ./ro/
      lang: ro
    - name: Русский
      link: ./ru/
      lang: ru
    - name: Español
      link: ./es/
      lang: es
    - name: 中文
      link: ./zh/
      lang: zh

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
        - locale: de
          name: Deutsch
        - locale: fr
          name: Français
        - locale: hi
          name: हिन्दी
        - locale: it
          name: Italiano
        - locale: ja
          name: 日本語
        - locale: pt
          name: Português
        - locale: ro
          name: Română
        - locale: ru
          name: Русский
        - locale: es
          name: Español
        - locale: zh
          name: 中文

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
