site_name: Emotions for Engineers
site_url: https://florindottudosedotcom.github.io/emotions-for-engineers/
repo_url: https://github.com/florindottudosedotcom/emotions-for-engineers

theme:
  name: material
  language: en
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.tracking
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link

extra_css:
- assets/css/custom.css

extra:
  alternate:
  - name: EN
    lang: en
    link: /
  - name: DE
    lang: de
    link: /de/
  - name: FR
    lang: fr
    link: /fr/
  - name: HI
    lang: hi
    link: /hi/
  - name: IT
    lang: it
    link: /it/
  - name: JA
    lang: ja
    link: /ja/
  - name: PT
    lang: pt
    link: /pt/
  - name: RO
    lang: ro
    link: /ro/
  - name: RU
    lang: ru
    link: /ru/
  - name: ES
    lang: es
    link: /es/
  - name: ZH
    lang: zh
    link: /zh/

plugins:
- search
- i18n:
    languages:
    - locale: en
      name: English
      default: true
    - locale: de
      name: Deutsch
    - locale: fr
      name: Français
    - locale: hi
      name: हिन्दी
    - locale: it
      name: Italiano
    - locale: ja
      name: 日本語
    - locale: pt
      name: Português
    - locale: ro
      name: Română
    - locale: ru
      name: Русский
    - locale: es
      name: Español
    - locale: zh
      name: 中文

markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
- Home: index.md
- Available Courses: courses.md
- About: about.md
- Collect Emotions:
  - Overview: collect-emotions/index.md
  - First Day Collecting: collect-emotions/01-first-day-collecting.md
  - Second Day Collecting: collect-emotions/02-second-day-collecting.md
- Welcome to Emotions for Engineers:
  - Overview: course-example/index.md
  - Introduction: course-example/01-introduction.md
  - Advanced Topics: course-example/02-advanced-topics.md
- 'Emotional Mastery: Unleashing Your Inner Balance':
  - Overview: emotional-mastery-unleashing-your-inner-balance/index.md
  - Chapter 1 Understanding Emotions 101: emotional-mastery-unleashing-your-inner-balance/01-chapter-1-understanding-emotions-101.md
  - Chapter 2 Recognizing And Labeling Emotions: emotional-mastery-unleashing-your-inner-balance/02-chapter-2-recognizing-and-labeling-emotions.md
  - Chapter 3 Understanding Emotional Triggers: emotional-mastery-unleashing-your-inner-balance/03-chapter-3-understanding-emotional-triggers.md
  - Chapter 4 Emotional Regulation Strategies: emotional-mastery-unleashing-your-inner-balance/04-chapter-4-emotional-regulation-strategies.md
  - Chapter 5 Emotional Expression And Boundaries: emotional-mastery-unleashing-your-inner-balance/05-chapter-5-emotional-expression-and-boundaries.md
  - Chapter 6 Building Emotional Resilience: emotional-mastery-unleashing-your-inner-balance/06-chapter-6-building-emotional-resilience.md
  - Chapter 7 Mastering Emotional Balance: emotional-mastery-unleashing-your-inner-balance/07-chapter-7-mastering-emotional-balance.md
- 'Tuning the Machines: Mastering Emotional Intelligence for Machinery Construction Engineers':
  - Overview: tuning-the-machines-mastering-emotional-intelligence-for-machinery-construction-engineers/index.md
  - Understanding The Intersection Of Emotional Intelligence And Machinery Construction Engineering: tuning-the-machines-mastering-emotional-intelligence-for-machinery-construction-engineers/01-understanding-the-intersection-of-emotional-intelligence-and-machinery-construction-engineering.md
  - Implementing Emotional Intelligence Into Machinery Design And Development: tuning-the-machines-mastering-emotional-intelligence-for-machinery-construction-engineers/02-implementing-emotional-intelligence-into-machinery-design-and-development.md
- 'Unlock the Power of Emotional Awareness: Collecting Your Daily Emotions':
  - Overview: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/index.md
  - Chapter 1 The Art Of Awareness: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/01-chapter-1-the-art-of-awareness.md
  - Emotional Cartography: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/02-emotional-cartography.md
  - The Power Of Reflection: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/03-the-power-of-reflection.md
  - Embracing The Full Spectrum: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/04-embracing-the-full-spectrum.md
  - The Language Of Emotions: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/05-the-language-of-emotions.md
  - The Wisdom Of Emotional Patterns: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/06-the-wisdom-of-emotional-patterns.md
  - The Art Of Integration: unlock-the-power-of-emotional-awareness-collecting-your-daily-emotions/07-the-art-of-integration.md
