site_name: My Awesome Course
site_url: https://florindottudosedotcom.github.io/emotions-for-engineers/
repo_url: https://github.com/florindottudosedotcom/emotions-for-engineers

theme:
  name: material
  language: en # Sets the default language for the site
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

extra:
  alternate:
    # Link to the English version
    - name: English
      link: /
      lang: en
    # Link to the German version
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search # The search plugin is required and must be listed first
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: de
          name: Deutsch
          build: true
