site_name: My Awesome Course
site_url: https://florindottudosedotcom.github.io/emotions-for-engineers/
repo_url: https://github.com/florindottudosedotcom/emotions-for-engineers

theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: de
          name: Deutsch
          build: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
